### ISSUE TITLE
Is there any more documentation?

### ISSUE THREAD

**Issue by xguse** [Brodinlab/cellgrid#1]
I am afraid that the "getting Started" section of the README is a bit sparse. And the information in your biorxiv paper is a bit too high level to be immediately applicable to your software.

Generally I can work out how you go about defining your schema, but I am a bit confused about your definition of specific learning algorithms in this stage as your paper says that these will be chosen after comparing the F1 scores of multiple methods. 

This is ONE example of the ambiguity that I personally see and am blocked by when trying to use your software. Is there a set of documentation that goes a bit further?

Thanks!

**Comment by nehcgnay** [comment]
Hello, it's a group of multiple classifiers. Each of them is corresponding to a cell type. 
Model of the classifier is defined by "model_class_name" in the schema file. This is a manually chosen from the candidates like random forest,  xgboost, etc.. The comparison is done by using the F1 scores.

**Comment by xguse** [comment]
OK so the way that I would compare "random-forest" and "xgb" methods for cell calling (for example) is to define a schema like this?



```
[
    {
        "name": "all-events",
        "parent": null,
        "model_class_name": "random-forest",
        "markers": [
            "Ce140Di",
            "Ir191Di"
        ]
    },
    {
        "name": "cells",
        "parent": "all-events",
        "model_class_name": "random-forest",
        "markers": [
            "CD45",
            "HLA-ABC",
            "CD57",
            "CD19",
            "CD5"
        ]
    },
    {
        "name": "cells",
        "parent": "all-events",
        "model_class_name": "xgb",
        "markers": [
            "CD45",
            "HLA-ABC",
            "CD57",
            "CD19",
            "CD5"
        ]
    }
]
```

Then just choose the one with the best F1, remove the poorer performer and build the next stage pointing back to "cells"?

**Comment by nehcgnay** [comment]
The config shall be separated as shown below. Then the one with best F1 is kept. 
In our experience xgb performs better over all. 

```
#cfg1
[
    {
        "name": "all-events",
        "parent": null,
        "model_class_name": "random-forest",
        "markers": [
            "Ce140Di",
            "Ir191Di"
        ]
    },
    {
        "name": "cells",
        "parent": "all-events",
        "model_class_name": "random-forest",
        "markers": [
            "CD45",
            "HLA-ABC",
            "CD57",
            "CD19",
            "CD5"
        ]
    }
]

#cfg2
[
    {
        "name": "all-events",
        "parent": null,
        "model_class_name": "random-forest",
        "markers": [
            "Ce140Di",
            "Ir191Di"
        ]
    },
    {
        "name": "cells",
        "parent": "all-events",
        "model_class_name": "xgb",
        "markers": [
            "CD45",
            "HLA-ABC",
            "CD57",
            "CD19",
            "CD5"
        ]
    }
]
```

**Comment by xguse** [comment]
Ahh I see. thanks!
