### ISSUE TITLE
Preprocessing options to classify new samples

### ISSUE THREAD

**Issue by MikhaelManurung** [Brodinlab/cellgrid#2]
Dear authors,

Thank you for writing the package. I think this approach holds great promise to streamline the automatic cell classification of cytometry data. I have several questions regarding the practical applications of this package.

- Where does `cellgrid` lie in your lab's CyTOF data analysis pipeline? 
    - Do you use it to classify cells in new samples (after training the algorithm on a reference dataset, for example), or
    - to classify cells from the same study after training the algorithm on a subset of the data?

- For classification of cells in new studies, what preprocessing option would you recommend to mitigate variability in signal intensities?

- Lastly, I notice that the F1-score for Plasmablasts is extremely low (~ .06). What causes this?

Thank you for taking the time to reply. I am looking forward to using this package in our lab! 

Best regards,
Mikhael

**Comment by nehcgnay** [comment]
Hello, Thank you for your interests! 
We use it for all samples. z-score transformation shall be applied on each file. 
Very little cells of Plasmablasts were included in that training data which causes the low score. It shall show a big improvement if more of those cells are added for the training.

**Comment by MikhaelManurung** [comment]
Thanks for the response!

So that was the cause. Just my two cents here, I think you should add that information to the manuscript. The extremely low F1-score is quite jarring for me and I cannot find the explanation anywhere in the manuscript.

I would like to ask more questions if you do not mind.
- What was the probability threshold that you use to assign the cells? How many cells were left unassigned?
- What software did you use to gate on tSNE plots?

**Comment by nehcgnay** [comment]
Thanks for the comments. 
We didn't try much on tuning the threshold and it's kept 0.5.  
Unassigned cells are usually 1~5%.  The number increases if you look deeper like Plasmablasts. 
We build a software for the manually gating, which will be opened later this year. 
The tSNE gating performances better than biaxial gating in our experiments.

**Comment by MikhaelManurung** [comment]
Thanks for the responses! I look forward for more exciting papers from your group.
